--- 
abstract: Authenticate Users against LDAP Directories
author: 
  - Adam Jacob <holoway@cpan.org>
build_requires: 
  Net::LDAP::Server::Test: 0.03
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Authentication-Store-LDAP
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst::Plugin::Authentication: 0.10003
  Net::LDAP: 0
version: 0.1002
